# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'rothoma2/wazuh'
  config.vm.box_version = '4.1.3'

  config.vm.boot_timeout = 600
  config.vm.hostname = 'wazuh'
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.network 'public_network', bridge: 'wlp0s20f3'
  config.vm.network 'private_network', ip: '192.168.56.10'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
    vb.memory = '4096'
    vb.name = 'Wazuh'
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.provision 'file', source: '../../ruleset/0010-rules_config.xml',
                              destination: '/var/ossec/etc/rules'

  config.vm.provision 'file', source: '../../ruleset/0040-auditd_decoders.xml',
                              destination: '/var/ossec/etc/decoders'

  config.vm.provision 'shell', inline: <<-SHELL, privileged: false
    sudo nmcli connection add type ethernet ifname eth0 con-name eth0-static \
    ipv4.addresses 192.168.56.10/24 \
    ipv4.gateway 192.168.56.1 \
    ipv4.dns "1.1.1.1 1.0.0.1" \
    ipv4.method manual

    # Bring the network connection up
    sudo nmcli connection up eth0-static

    # Optional: restart the connection to apply
    sudo nmcli connection down eth0-static
    sudo nmcli connection up eth0-static

    ## Bashrc tweaks ##
    # Set CTRL+L to clear
    echo 'bind -x '"'"'"\C-l":clear'"'"'' >> ~/.bashrc
    # Avoid 'xterm-kitty': unknown terminal type
    echo "TERM=xterm-256color" >> ~/.bashrc
  SHELL
end
